language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower gulp-cli web-component-tester
- npm install
- bower install
script: gulp wct:test
deploy:
  provider: npm
  email: malhar.deshpande18@gmail.com
  skip_cleanup: true
  api_key:
    secure: QxJhgxM9HFrgxk6MBuTKP3+4VLOASCIL500YhGojjxRC4EKqQcJ9dpZlqry/hZgVmYLwJDinoWlIlCBDsKZhgAfSESL4WZowXYsLlzE3eQyaYzZIuLqXQvU22V82FEzMFrFJhPOpnUhGw7MSjV+5MJh/ZUFALIam2o3iWf+OdsAgdgCgr9HdfoIQ5a6ynbjrkkItHIaa5FgtzX1lvFsyYDn2W/NBrebh32wTF3Qh2nB7wX6s6cYF5jsaJBwYVXo8ByIJOny4MtknrLe7F9yyE929B97aiBCbICt8DgLmdiZmILZb8eJafcy/Ze1OSeKJ/beA/89yLbMKdfwfbGgCH0zjjLT+Uzr0NrBz+0kYYCtplXBScKxJFzj9uR4KFVMB2cgA4PP71/QXW6bQcn9FNqWcL+ZH1jV1Bb2wa/8EYyezWP5IPVDvi+m7jUxq1pAlYO8ok950yL/avyIvT+mM0v11neY5shN8xuFHVpBirs0j4VDmeIxg9pv22niA07yKqfA/r8696mCos1C4BxeMEJoMvx8rxHG5idIYBAdf+NiBqS/e+Rc5wQuocXrxc8dgSNoYw2JpSFpK73O+7OA9xkhkodcMn+uEguVJRThF42v1LyR/PGbdw4b8zHkzhLgg3ey9ROnU8LDjjmtcvQaxpJbvHNwJs6pRIjwJyKBhx7k=
true:
  branch: master
env:
  global:
  - secure: fKM9y5uHPYPGeTTPuDE/u2NkIcC5ocg1440N/XJs4jz8Jql3lMqk1sphiLFeemDm3eLG7E5FacqgrnuZt4GVF57Xz76+gVYdiGuxb/VHPZze97M64Lbxbyp3sZ5XjaL2f/P18KE1Gy+R0nrhDJfhPa2DQPM19Yn7xCKr+/teY9r0sMai9asOcigsNkMHMcEnp/LiWGoGLVJRhlHdYx4KZKBD35ZW456OXzmXFt/4m0Te+xbSZFn4+AZuJDib46mgRPcpiQF+nkDQosLfDK0z9vArl0osMeWf3xYFHyIEbk5Hh6ZIFi2x2om0IQ5nnaCPmexY20ndb7tONd9BiKGPfpQ/ENFqHQl1CMy13AJyUYrER52vmAHubpmnALpZ7zGISHV6sWYhZKzUgg/XvxgXLNLomB6F2NtX/don+eZ7BksZrM+shu8BBY2xyE2IKvJ/Ef3cPJNQ2Uxpsy4ijFF3XJom4pLLqM8Rsd0nxDu1yNEGB83VSSxLmKWEYt6Tk1mQWJweCgGVk5N0WNrvDQtmRmL6DnfWZwFdQES31HjEYPsWzKrwTmtn9dlhJWusvVHMS/bP+31siNtrTr3poozKPunTq+4mCd3IJtQHJ0Ee+EEBmc0vygXPMOeZvni/lSmXGTD8Bfctofkmu2rGVqk1bXi5Ng+eKvhqPhSh9oeki0U=
  - secure: hqMl4ttUmhTQuWJcC3eFzNbqPPYtEwgoKrh0c2d5y+nXAO+JhpA6xlaD8Tb7bxNcMllL5rOI7lkZ6aWPjw0b/yHwD+EHPRPlq8l/0ibjS74QamqwqWE2mIKG98WwGsAzlH8XehrTSrWeSqKJ/ulWEcaFziVX9NQQyhGaPVu8gKGJRsyLs8x/lCtY9+4LfCWK1iwTsQsFYico8kMj38TdzizL5qYIrlE0MUYX4DYwcL3amTBMB+v4UiBacadSYnxVbPqZt70HV1vivUefzMFfr0fxsE6YE8/uLCQe0B+W9GgCxVKLlWRKPB+twOWtkmpoNNU52zDnYnTRSQq3Jt2d79yKQBOVu4fUm/iyoUMSeKcmBviPA/opYUvKnORd9+Y5poDwdMlUOAHgov5miN+kX4A634yAUiMMsgtKAG35vsU0uql8UfU28n+4Zoa0r5secSNDg8WzlVbzBjILv7QfM0TTLuwE0T38J9yV29MzhrmauAllXopBsXIM3kEEdQcYWXytmQDjJImHI6R7zriTN9Th/tRSUhwIPZtH56n85nSDeq5B4FntH7HniA0LW5/5GQHcIw+iD8Lkm9zo8ccxghp/jn4Im1CoY9+uV/FjEFr4IbwDY2Sww0grfh8Ps5zwx7Pz2bsRXfRnjGrwE8y1aUieo1TAKXDDMI+NW9WY0jw=
